language: python

python:
    - '3.6'
    - '3.7'
    - '3.8'

install: pip install -e ."[dev]"

script:
    - flake8 pingpang/*.py
    - flake8 test/*.py
    - pytest --cov=pingpang

deploy:
    provider: pypi
    username: __token__
    password:
        secure: R3y1azBSMvXnhfLPhvEsvs6jMEYuNQCO+49yXYacpPFv6667VcJ59EDZmEFfJPq+kwnp/yGhGXnZRtHYl9V56EPuCkyKL/PWE03DYpGJ2y52jHqX4ANEE96CltA02af2IRroXRtd8BqLeLZCaKDtM/u4gfsSzxYpxqJsJ2PoYr3+V/YvGy7JIgQ/MqJwLMJYaQgV+Ii/SmpV8n7MraInGKnx/q0qqVzJ6GiQfxWNuxJX1w2LZyyuZikXNoyanUtrAGn5wQeRXBljQ/snHbCsJw2tRp07K/C66THWBJ+Rch9TPfhkgSWpb2qrVydb2wn4zGvYA4omb+wZu6QHejV6yKOLi2XEXsyP5Zwa2FSXr8SBIvnF77ksy/As/PDpx4rryWQFPhVlGP33Fid/BGA+8ubjBFJyJ/jv6xorcanw+B8AozSCZ7IetgrJlstTm7lhINUh+A1daYDuVtGf1N66t47ZnROUdO8KV67D9DWbX9UloCT4Q8trfIbFLovQ+ZE+DpCaTegAhRzgaSZeXfWs5jG8VhzHBbnXNb7UHoAIPnv6e/NZKmTmlfgtfOKUaBPWweYvNhJABnFWU/Tr/iYCgyL02Fn0ApLZtWIFM1Vn7lcpNtTFZczUKL0PQcqUAmh4/ohQqNYv1eGKUa/hm31yUzNCZsTeHHPB6Yy51evYGIc=
    on:
        tags: true
    skip_existing: true

after_success:
    - coveralls
